Repository snowone4426/Body_Manager_server, pull requests merged in 2022-12, with the labels that each got.

#26 [정은] ADD | create ptprogram
  src/main/java/net/ict/bodymanager/dto/CabinetDTO.java
  src/main/java/net/ict/bodymanager/dto/FoodDTO.java
  src/main/java/net/ict/bodymanager/dto/PTProgramDTO.java
  src/main/java/net/ict/bodymanager/entity/Member.java
  src/main/java/net/ict/bodymanager/repository/FoodRepository.java
  src/main/java/net/ict/bodymanager/service/FileServiceImpl.java
  src/main/java/net/ict/bodymanager/service/FoodService.java
  src/main/java/net/ict/bodymanager/service/FoodServiceImpl.java
  src/main/java/net/ict/bodymanager/service/LoginServiceImpl.java
  src/test/java/net/ict/bodymanager/entity/entity.java
Labels: 정은

#8 인바디 완료
  build.gradle
  src/main/java/net/ict/bodymanager/controller/InbodyController.java
  src/main/java/net/ict/bodymanager/dto/InbodyDTO.java
  src/main/java/net/ict/bodymanager/dto/InbodyRequestDTO.java
  src/main/java/net/ict/bodymanager/entity/Inbody.java
  src/main/java/net/ict/bodymanager/repository/FileRepository.java
  src/main/java/net/ict/bodymanager/repository/InbodyRepository.java
  src/main/java/net/ict/bodymanager/repository/MemberRepository.java
  src/main/java/net/ict/bodymanager/service/InbodyService.java
  src/main/java/net/ict/bodymanager/service/InbodyServiceImpl.java
  src/test/java/net/ict/bodymanager/entity/entity.java
  src/test/java/net/ict/bodymanager/service/InbodyTest.java
Labels: 원근

#29 [준영] ADD | 로그인, 아이디 찾기, 비밀번호 찾기 인증번호 발송 요청, 비밀번호 변경, 이메일 중복 확인, 핸드폰 번…
  src/main/java/net/ict/bodymanager/config/SecurityConfig.java
  src/main/java/net/ict/bodymanager/config/WebConfig.java
  src/main/java/net/ict/bodymanager/config/WebSecurityConfig.java
  src/main/java/net/ict/bodymanager/controller/MailController.java
  src/main/java/net/ict/bodymanager/controller/MemberController.java
  src/main/java/net/ict/bodymanager/controller/TestController.java
  src/main/java/net/ict/bodymanager/controller/UpDownController.java
  src/main/java/net/ict/bodymanager/controller/advice/ApiControllerAdvice.java
  src/main/java/net/ict/bodymanager/dto/MailDTO.java
  src/main/java/net/ict/bodymanager/dto/MemberDTO.java
  src/main/java/net/ict/bodymanager/dto/upload/UploadFileDTO.java
  src/main/java/net/ict/bodymanager/dto/upload/UploadResultDTO.java
  src/main/java/net/ict/bodymanager/entity/Member.java
  src/main/java/net/ict/bodymanager/entity/MemberRole.java
  src/main/java/net/ict/bodymanager/filter/JwtAuthenticationFilter.java
  src/main/java/net/ict/bodymanager/filter/JwtTokenProvider.java
  src/main/java/net/ict/bodymanager/repository/MemberRepository.java
  src/main/java/net/ict/bodymanager/service/CustomUserDetailService.java
  src/main/java/net/ict/bodymanager/service/EmailService.java
  src/main/java/net/ict/bodymanager/service/EmailServiceImpl.java
  src/main/java/net/ict/bodymanager/service/FileServiceImpl.java
  src/main/java/net/ict/bodymanager/service/LoginServiceImpl.java
  src/main/java/net/ict/bodymanager/service/MemberService.java
  src/main/java/net/ict/bodymanager/service/MemberServiceImpl.java
  src/main/java/net/ict/bodymanager/util/RedisUtil.java
  src/main/resources/templates/AfterMail.html
  src/main/resources/templates/SendMail.html
  src/main/resources/templates/bad.html
  src/main/resources/templates/good.html
Labels: 준영

#30 [원근] Feat/account
  src/main/java/net/ict/bodymanager/controller/AccountController.java
  src/main/java/net/ict/bodymanager/dto/OrderListDTO.java
  src/main/java/net/ict/bodymanager/entity/Cabinet.java
  src/main/java/net/ict/bodymanager/entity/OrderInfo.java
  src/main/java/net/ict/bodymanager/repository/CabinetRepository.java
  src/main/java/net/ict/bodymanager/repository/OrderRepository.java
  src/main/java/net/ict/bodymanager/repository/PTMemberRepository.java
  src/main/java/net/ict/bodymanager/repository/SubscribeRepository.java
  src/main/java/net/ict/bodymanager/service/AccountService.java
  src/main/java/net/ict/bodymanager/service/AccountServiceImpl.java
Labels: 원근
